CREATE TABLE memoir_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  nickname TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE memoir_posts
  ADD COLUMN
    author_id INTEGER REFERENCES memoir_users(id)
    ON DELETE SET NULL;
